version: '3.5'

services:
  backend:
    build: ./backend
    container_name: kamil_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DJANGO_SECRET_KEY=your-secret-key-here-change-in-production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kamil_jewelry
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: kamil_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: kamil_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kamil_jewelry
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
