# Generated by Django 4.2.7 on 2025-09-03 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('mobile_image', models.ImageField(blank=True, upload_to='banners/mobile/', verbose_name='Изображение для мобильных')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('link_url', models.URLField(blank=True, verbose_name='Ссылка баннера')),
                ('position', models.CharField(choices=[('hero', 'Главный баннер'), ('promo', 'Промо баннер'), ('category', 'Баннер категории')], default='hero', max_length=20, verbose_name='Позиция')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('show_from', models.DateTimeField(blank=True, null=True, verbose_name='Показывать с')),
                ('show_until', models.DateTimeField(blank=True, null=True, verbose_name='Показывать до')),
                ('background_color', models.CharField(default='#ffffff', help_text='Hex код цвета', max_length=7, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#000000', help_text='Hex код цвета', max_length=7, verbose_name='Цвет текста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['position', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы-Ответы',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KAMIL Jewelry', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, verbose_name='Описание сайта')),
                ('logo', models.ImageField(blank=True, upload_to='settings/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/', verbose_name='Фавикон')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp номер')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('currency', models.CharField(default='₸', max_length=10, verbose_name='Валюта')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Налоговая ставка')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бесплатная доставка от')),
                ('working_hours', models.TextField(blank=True, default='Пн-Вс: 10:00 - 22:00', verbose_name='Режим работы')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('yandex_metrica_id', models.CharField(blank=True, max_length=50, verbose_name='Yandex Metrica ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Аватар')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Оценка')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок отзыва')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
